[package]
name = "nativeconfig"
version = "0.1.0"
edition = "2021"

[lib]
name = "nativeconfig"
crate-type = ["cdylib"]

[dependencies]
jni = "0.21"
once_cell = "1.19"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = "symbols"
